import { Schema, model, models } from 'mongoose';

const resultSchema = new Schema(
  {
    student_id: { type: String, required: true },
    student_name: { type: String, required: true },
    session: { type: String, required: true },
    sex: { type: String, required: true },
    classes: { type: String, required: true },
    term: { type: String, required: true },
    class_abc: { type: String, required: true },
    teacher: { type: String, required: true },
    maths: { type: Number, required: true },
    eng: { type: Number, required: true },
    biology: { type: Number },
    chemistry: { type: Number },
    physic: { type: Number },
    f_maths: { type: Number },
    civic: { type: Number },
    eco: { type: Number },
    account: { type: Number },
    bk_keeping: { type: Number },
    fishries: { type: Number },
    commerce: { type: Number },
    govt: { type: Number },
    yoruba: { type: Number },
    eng_lit: { type: Number },
    history: { type: Number },
    geo: { type: Number },
    home_eco: { type: Number },
    agric: { type: Number },
    data_pro: { type: Number },
    position: {
      maths: { type: String, default: '' },
      eng: { type: String, default: '' },
      biology: { type: String },
      chemistry: { type: String },
      physic: { type: String },
      f_maths: { type: String },
      civic: { type: String },
      eco: { type: String },
      account: { type: String },
      bk_keeping: { type: String },
      fishries: { type: String },
      commerce: { type: String },
      govt: { type: String },
      yoruba: { type: String },
      eng_lit: { type: String },
      history: { type: String },
      geo: { type: String },
      home_eco: { type: String },
      agric: { type: String },
      data_pro: { type: String },
    },
    exam: {
      maths: { type: Number, default: 0, required: true },
      eng: { type: Number, default: 0, required: true },
      biology: { type: Number },
      chemistry: { type: Number },
      physic: { type: Number },
      f_maths: { type: Number },
      civic: { type: Number },
      eco: { type: Number },
      account: { type: Number },
      bk_keeping: { type: Number },
      fishries: { type: Number },
      commerce: { type: Number },
      govt: { type: Number },
      yoruba: { type: Number },
      eng_lit: { type: Number },
      history: { type: Number },
      geo: { type: Number },
      home_eco: { type: Number },
      agric: { type: Number },
      data_pro: { type: Number },
      no_in_class: { type: Number },
      total_term_score: { type: Number },
      position: { type: String, default: '' },
      principal: { type: String, default: '' },
    },
  },
  { timestamps: true }
);

const Result = models.result || model('result', resultSchema);
export default Result;
